"""Render a runnable Reflex views module (state + pages) from a Django model."""

from __future__ import annotations

from collections.abc import Sequence

from django.db import models

from reflex_django.scaffold.introspect import ScaffoldField, editable_fields
from reflex_django.state.options import pluralize_model_name


def _select_fields(
    model: type[models.Model],
    names: Sequence[str] | None,
) -> list[ScaffoldField]:
    available = editable_fields(model)
    if not names:
        return available
    by_name = {f.name: f for f in available}
    selected: list[ScaffoldField] = []
    missing: list[str] = []
    for raw in names:
        name = str(raw).strip()
        if not name:
            continue
        field = by_name.get(name)
        if field is None:
            missing.append(name)
            continue
        selected.append(field)
    if missing:
        valid = ", ".join(sorted(by_name)) or "(none)"
        msg = (
            f"Unknown editable field(s) for {model.__name__}: "
            f"{', '.join(missing)}. Available: {valid}."
        )
        raise ValueError(msg)
    return selected


def _form_widget(state: str, field: ScaffoldField) -> str:
    """Render a single labelled form control bound to an editable state var."""
    var = f"{state}.{field.name}"
    setter = f"{state}.set_{field.name}"
    if field.widget == "bool":
        return (
            f"        rx.checkbox(\n"
            f'            "{field.label}",\n'
            f"            checked={var},\n"
            f"            on_change={setter},\n"
            f"        ),"
        )
    if field.widget == "textarea":
        control = (
            f"        rx.text_area(\n"
            f'            placeholder="{field.label}",\n'
            f"            value={var},\n"
            f"            on_change={setter},\n"
            f"        ),"
        )
    else:
        input_type = "number" if field.widget == "number" else "text"
        control = (
            f"        rx.input(\n"
            f'            placeholder="{field.label}",\n'
            f"            value={var},\n"
            f"            on_change={setter},\n"
            f'            type="{input_type}",\n'
            f"        ),"
        )
    return f'        rx.text("{field.label}", size="2"),\n{control}'


def render_scaffold(
    model: type[models.Model],
    *,
    fields: Sequence[str] | None = None,
    include_serializer: bool = False,
    paginate_by: int | None = 20,
    search_fields: Sequence[str] | None = None,
    route: str | None = None,
) -> str:
    """Return source for a views module exposing CRUD state and pages for *model*.

    Args:
        model: The Django model class to scaffold.
        fields: Editable field names to expose; defaults to all editable fields.
        include_serializer: Emit an explicit ``ReflexDjangoModelSerializer``.
        paginate_by: Page size (``None`` disables pagination UI).
        search_fields: Fields for text search; defaults to text fields.
        route: Page route; defaults to the pluralized model name.
    """
    selected = _select_fields(model, fields)
    if not selected:
        msg = f"{model.__name__} has no editable fields to scaffold."
        raise ValueError(msg)

    name = model.__name__
    lower = model._meta.model_name or name.lower()
    state = f"{name}State"
    plural = pluralize_model_name(name)
    route = route or plural
    field_names = [f.name for f in selected]

    if search_fields is None:
        resolved_search = [f.name for f in selected if f.widget in ("text", "textarea")]
    else:
        resolved_search = [str(s).strip() for s in search_fields if str(s).strip()]

    model_module = model.__module__

    lines: list[str] = [
        f'"""Auto-generated by `reflex django scaffold '
        f"{model._meta.app_label}.{name}`.",
        "",
        "This is a starting point — edit freely. Re-run with `--force` to overwrite.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import reflex as rx",
        "from reflex_django.states import ModelState",
    ]
    if include_serializer:
        lines.append(
            "from reflex_django.serializers import ReflexDjangoModelSerializer"
        )
    lines += [
        "",
        f"from {model_module} import {name}",
        "",
        "",
    ]

    if include_serializer:
        ser_fields = ", ".join(f'"{n}"' for n in ["id", *field_names])
        lines += [
            f"class {name}Serializer(ReflexDjangoModelSerializer):",
            "    class Meta:",
            f"        model = {name}",
            f"        fields = ({ser_fields})",
            "",
            "",
        ]

    lines.append(f"class {state}(ModelState):")
    lines.append(f"    model = {name}")
    fields_repr = ", ".join(f'"{n}"' for n in field_names)
    lines.append(f"    fields = [{fields_repr}]")
    if paginate_by:
        lines.append(f"    paginate_by = {int(paginate_by)}")
    if resolved_search:
        search_repr = ", ".join(f'"{n}"' for n in resolved_search)
        trailing = "," if len(resolved_search) == 1 else ""
        lines.append(f"    search_fields = ({search_repr}{trailing})")
    if include_serializer:
        lines += [
            "",
            "    class Meta:",
            f"        serializer = {name}Serializer",
        ]
    lines += ["", ""]

    header_cells = "\n".join(
        f'                    rx.table.column_header_cell("{f.label}"),'
        for f in selected
    )
    body_cells = "\n".join(
        f'        rx.table.cell(row["{f.name}"].to_string()),' for f in selected
    )
    lines += [
        f"def {lower}_row(row: dict) -> rx.Component:",
        "    return rx.table.row(",
        body_cells,
        "        rx.table.cell(",
        "            rx.hstack(",
        "                rx.button(",
        '                    "Edit",',
        f'                    on_click=lambda: {state}.load(row["id"]),',
        '                    size="1",',
        "                ),",
        "                rx.button(",
        '                    "Delete",',
        f'                    on_click=lambda: {state}.delete(row["id"]),',
        '                    size="1",',
        '                    color_scheme="red",',
        "                ),",
        '                spacing="2",',
        "            ),",
        "        ),",
        "    )",
        "",
        "",
    ]

    form_widgets = "\n".join(_form_widget(state, f) for f in selected)
    lines += [
        f"def {lower}_form() -> rx.Component:",
        "    return rx.vstack(",
        f"        rx.cond(\n            {state}.editing_id >= 0,\n"
        f'            rx.heading("Edit {name}", size="4"),\n'
        f'            rx.heading("New {name}", size="4"),\n        ),',
        form_widgets,
        "        rx.hstack(",
        f'            rx.button("Save", on_click={state}.save),',
        f'            rx.button("Cancel", on_click={state}.cancel_edit, '
        'variant="soft"),',
        '            spacing="2",',
        "        ),",
        f'        rx.cond(\n            {state}.error != "",\n'
        f'            rx.callout({state}.error, color_scheme="red"),\n        ),',
        '        spacing="2",',
        '        width="100%",',
        "    )",
        "",
        "",
    ]

    list_children: list[str] = [
        f'        rx.heading("{plural.title()}", size="6"),',
    ]
    if resolved_search:
        list_children.append(
            "        rx.input(\n"
            '            placeholder="Search...",\n'
            f"            value={state}.search,\n"
            f"            on_change={state}.set_search,\n"
            f"            on_blur={state}.refresh,\n"
            "        ),"
        )
    list_children += [
        "        rx.table.root(",
        "            rx.table.header(",
        "                rx.table.row(",
        header_cells,
        '                    rx.table.column_header_cell("Actions"),',
        "                ),",
        "            ),",
        f"            rx.table.body(rx.foreach({state}.data, {lower}_row)),",
        '            width="100%",',
        "        ),",
    ]
    if paginate_by:
        list_children.append(
            "        rx.hstack(\n"
            "            rx.button(\n"
            '                "Prev",\n'
            f"                on_click=lambda: {state}.paginate(page={state}.page - 1),\n"
            f"                disabled={state}.page <= 1,\n"
            '                size="1",\n'
            "            ),\n"
            f'            rx.text({state}.page.to_string(), " / ", '
            f"{state}.page_count.to_string()),\n"
            "            rx.button(\n"
            '                "Next",\n'
            f"                on_click=lambda: {state}.paginate(page={state}.page + 1),\n"
            f"                disabled={state}.page >= {state}.page_count,\n"
            '                size="1",\n'
            "            ),\n"
            '            spacing="2",\n'
            '            align="center",\n'
            "        ),"
        )
    lines += [
        f"def {lower}_list() -> rx.Component:",
        "    return rx.vstack(",
        *list_children,
        '        spacing="3",',
        '        width="100%",',
        "    )",
        "",
        "",
        f"def {lower}_page() -> rx.Component:",
        "    return rx.container(",
        "        rx.vstack(",
        f"            {lower}_list(),",
        "            rx.divider(),",
        f"            {lower}_form(),",
        '            spacing="4",',
        '            width="100%",',
        "        ),",
        '        size="3",',
        "    )",
        "",
        "",
        "# Register this page in your app entry (e.g. shop/shop.py):",
        "#   app.add_page(",
        f"#       {lower}_page,",
        f'#       route="/{route}",',
        f'#       title="{plural.title()}",',
        f"#       on_load={state}.refresh,",
        "#   )",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_scaffold"]
