"""Patch Reflex's generated Vite config to proxy Django path prefixes in dev."""

from __future__ import annotations

import json
import re
from pathlib import Path

from reflex_django.asgi import RESERVED_REFLEX_PREFIXES

_PROXY_MARKER = "reflex-django-proxy"
_PROXY_PLUGIN_MARKER = "reflex-django-proxy-plugin"
_PROXY_PLUGIN_FILENAME = "vite-plugin-reflex-django-proxy.js"
_PROXY_PLUGIN_IMPORT = (
    'import { reflexDjangoProxyPlugin } from "./vite-plugin-reflex-django-proxy.js";'
)
_PROXY_BLOCK_RE = re.compile(
    r"\n\s*// reflex-django-proxy.*?\n\s*proxy:\s*\{[^}]*\},?\n",
    re.DOTALL,
)


def _normalize_proxy_prefix(prefix: str) -> str:
    if not prefix.startswith("/"):
        prefix = "/" + prefix
    if len(prefix) > 1 and prefix.endswith("/"):
        prefix = prefix.rstrip("/")
    return prefix


def _normalized_prefixes(prefixes: tuple[str, ...]) -> tuple[str, ...]:
    return tuple(
        dict.fromkeys(
            _normalize_proxy_prefix(p) for p in prefixes if p and str(p).strip()
        )
    )


_WS_PROXY_PREFIXES = frozenset({"/_event"})
_ENV_JSON = "env.json"


def vite_dev_proxy_prefixes(django_prefixes: tuple[str, ...]) -> tuple[str, ...]:
    """Django URL prefixes plus Reflex backend endpoints for ``server.proxy``."""
    combined = (*django_prefixes, *RESERVED_REFLEX_PREFIXES)
    return _normalized_prefixes(combined)


def _proxy_entry_line(prefix: str, target: str) -> str:
    target_json = json.dumps(target)
    if prefix in _WS_PROXY_PREFIXES:
        return (
            f'      "{prefix}": '
            f"{{ target: {target_json}, ws: true, changeOrigin: true }}"
        )
    return f'      "{prefix}": {{ target: {target_json}, changeOrigin: true }}'


def render_proxy_plugin_js(*, target: str, prefixes: tuple[str, ...]) -> str:
    """Return source for ``vite-plugin-reflex-django-proxy.js``."""
    unique = _normalized_prefixes(prefixes)
    prefixes_json = json.dumps(list(unique))
    target_json = json.dumps(target.rstrip("/"))
    return f"""// {_PROXY_PLUGIN_MARKER} (auto-generated by reflex-django — do not edit)
import http from "node:http";
import https from "node:https";
import {{ URL }} from "node:url";

const TARGET = {target_json};
const PREFIXES = {prefixes_json};

function matchesPrefix(pathname) {{
  for (const prefix of PREFIXES) {{
    if (pathname === prefix || pathname.startsWith(prefix + "/")) {{
      return true;
    }}
  }}
  return false;
}}

export function reflexDjangoProxyPlugin() {{
  const targetUrl = new URL(TARGET);
  const client = targetUrl.protocol === "https:" ? https : http;

  return {{
    name: "reflex-django-proxy",
    enforce: "pre",
    configureServer(server) {{
      server.middlewares.use((req, res, next) => {{
        const pathname = (req.url ?? "/").split("?")[0];
        if (!matchesPrefix(pathname)) {{
          return next();
        }}

        const options = {{
          hostname: targetUrl.hostname,
          port:
            targetUrl.port ||
            (targetUrl.protocol === "https:" ? 443 : 80),
          path: req.url,
          method: req.method,
          headers: {{
            ...req.headers,
            host: targetUrl.host,
          }},
        }};

        const proxyReq = client.request(options, (proxyRes) => {{
          res.writeHead(proxyRes.statusCode ?? 502, proxyRes.headers);
          proxyRes.pipe(res, {{ end: true }});
        }});

        proxyReq.on("error", (err) => {{
          if (!res.headersSent) {{
            res.statusCode = 502;
            res.end(`reflex-django proxy error: ${{err.message}}`);
          }}
        }});

        req.pipe(proxyReq, {{ end: true }});
      }});
    }},
  }};
}}
"""


def inject_vite_dev_proxy(
    content: str,
    *,
    target: str,
    prefixes: tuple[str, ...],
) -> str:
    """Inject ``server.proxy`` rules into a generated ``vite.config.js``."""
    content = _PROXY_BLOCK_RE.sub("\n", content)

    unique_prefixes = _normalized_prefixes(prefixes)
    if not unique_prefixes:
        return content

    target = target.rstrip("/")
    proxy_entries = ",\n".join(
        _proxy_entry_line(prefix, target) for prefix in unique_prefixes
    )
    proxy_block = (
        f"\n    // {_PROXY_MARKER} (auto-generated by reflex-django)\n"
        f"    proxy: {{\n{proxy_entries},\n    }},\n"
    )

    match = re.search(r"server:\s*\{", content)
    if match is None:
        return content

    brace_pos = match.end() - 1
    newline = content.find("\n", brace_pos)
    insert_at = newline + 1 if newline != -1 else match.end()
    return content[:insert_at] + proxy_block + content[insert_at:]


def inject_vite_proxy_plugin(content: str) -> str:
    """Register :func:`reflexDjangoProxyPlugin` before React Router in Vite plugins."""
    if "reflexDjangoProxyPlugin" in content:
        return content

    if _PROXY_PLUGIN_IMPORT not in content:
        content = _PROXY_PLUGIN_IMPORT + "\n" + content

    return re.sub(
        r"plugins:\s*\[",
        "plugins: [\n    reflexDjangoProxyPlugin(),",
        content,
        count=1,
    )


def patch_vite_config(
    content: str,
    *,
    target: str,
    prefixes: tuple[str, ...],
) -> str:
    """Apply plugin import, pre-middleware plugin, and ``server.proxy`` rules."""
    content = inject_vite_proxy_plugin(content)
    all_prefixes = vite_dev_proxy_prefixes(prefixes)
    return inject_vite_dev_proxy(content, target=target, prefixes=all_prefixes)


def patch_env_json_for_frontend_proxy(
    web_dir: Path,
    *,
    frontend_port: int,
    backend_port: int,
) -> bool:
    """Point ``env.json`` API URLs at the Vite port (proxied to the Reflex backend)."""
    env_path = Path(web_dir) / "env.json"
    if not env_path.is_file():
        return False

    raw = env_path.read_text(encoding="utf-8")
    backend_host = f"localhost:{backend_port}"
    frontend_host = f"localhost:{frontend_port}"
    if f"localhost:{frontend_port}" in raw and f"localhost:{backend_port}" not in raw:
        return False

    updated = raw.replace(f"http://{backend_host}", f"http://{frontend_host}")
    updated = updated.replace(f"ws://{backend_host}", f"ws://{frontend_host}")
    if updated == raw:
        return False

    env_path.write_text(updated, encoding="utf-8")
    return True


def _vite_proxy_is_complete(content: str) -> bool:
    return (
        "reflexDjangoProxyPlugin()" in content
        and _PROXY_MARKER in content
        and '"/_event"' in content
        and "ws: true" in content
    )


def ensure_vite_django_dev_proxy(
    web_dir: Path,
    *,
    target: str,
    prefixes: tuple[str, ...],
    frontend_port: int | None = None,
    backend_port: int | None = None,
    patch_env: bool = False,
) -> bool:
    """Write the proxy plugin file and patch ``.web/vite.config.js``.

    React Router's ``react-router dev`` handles unknown routes before Vite's
    ``server.proxy``; the generated Vite plugin proxies in middleware first.

    Returns:
        ``True`` when any file was created or updated.
    """
    unique = _normalized_prefixes(prefixes)
    if not unique:
        return False

    web_dir = Path(web_dir)
    changed = False

    plugin_path = web_dir / _PROXY_PLUGIN_FILENAME
    plugin_source = render_proxy_plugin_js(target=target, prefixes=unique)
    if not plugin_path.is_file() or plugin_path.read_text(encoding="utf-8") != plugin_source:
        plugin_path.write_text(plugin_source, encoding="utf-8")
        changed = True

    vite_path = web_dir / "vite.config.js"
    if not vite_path.is_file():
        return changed

    content = vite_path.read_text(encoding="utf-8")
    if not _vite_proxy_is_complete(content):
        updated = patch_vite_config(content, target=target, prefixes=unique)
        if updated != content:
            vite_path.write_text(updated, encoding="utf-8")
            changed = True

    if patch_env and frontend_port is not None and backend_port is not None:
        if patch_env_json_for_frontend_proxy(
            web_dir,
            frontend_port=frontend_port,
            backend_port=backend_port,
        ):
            changed = True

    return changed


def ensure_vite_django_dev_proxy_from_config() -> bool:
    """Patch ``.web/vite.config.js`` using the active Reflex config and plugin.

    In :class:`~reflex_django.routing.UrlRoutingMode.DJANGO_OUTER` (the default),
    Django serves ``/`` directly and reverse-proxies it to Vite via
    :class:`reflex_django.views.mount.ReflexMountView`; the browser never talks
    to Vite at ``localhost:<frontend_port>`` itself, so Vite does not need
    Django-aware ``server.proxy`` rules. The patch is a no-op in that mode.
    """
    from reflex.utils import prerequisites
    from reflex_base.config import get_config
    from reflex_base.utils import console

    from reflex_django.plugin import ReflexDjangoPlugin
    from reflex_django.routing import UrlRoutingMode, resolve_url_routing

    routing_mode = resolve_url_routing()
    if routing_mode == UrlRoutingMode.DJANGO_OUTER:
        # Django is the outer ASGI app; Vite is reverse-proxied through Django.
        # Patching Vite to proxy backend paths would create a request loop.
        return False

    web_dir = Path(prerequisites.get_web_dir())
    if not web_dir.is_dir():
        return False

    config = get_config()
    plugin = next(
        (p for p in (config.plugins or ()) if isinstance(p, ReflexDjangoPlugin)),
        None,
    )
    if plugin is None:
        return False

    prefixes = plugin._all_prefixes()
    if not prefixes:
        return False

    django_led = routing_mode == UrlRoutingMode.DJANGO_LED
    changed = ensure_vite_django_dev_proxy(
        web_dir,
        target=config.api_url.rstrip("/"),
        prefixes=prefixes,
        frontend_port=config.frontend_port,
        backend_port=config.backend_port,
        patch_env=django_led,
    )
    if changed:
        console.info(
            "reflex-django patched .web/vite.config.js for Django admin/API proxies."
        )
    return changed


# Backwards-compatible alias
def ensure_vite_dev_proxy_file(
    vite_config_path: Path,
    *,
    target: str,
    prefixes: tuple[str, ...],
) -> bool:
    """Patch ``vite.config.js`` and sibling proxy plugin under the same directory."""
    return ensure_vite_django_dev_proxy(
        vite_config_path.parent,
        target=target,
        prefixes=prefixes,
    )
