"""Patch Reflex's generated Vite config to proxy Django path prefixes in dev."""

from __future__ import annotations

import json
import re

_PROXY_MARKER = "reflex-django-proxy"
_PROXY_BLOCK_RE = re.compile(
    r"\n\s*// reflex-django-proxy.*?\n\s*proxy:\s*\{[^}]*\},?\n",
    re.DOTALL,
)


def _normalize_proxy_prefix(prefix: str) -> str:
    if not prefix.startswith("/"):
        prefix = "/" + prefix
    if len(prefix) > 1 and prefix.endswith("/"):
        prefix = prefix.rstrip("/")
    return prefix


def inject_vite_dev_proxy(
    content: str,
    *,
    target: str,
    prefixes: tuple[str, ...],
) -> str:
    """Inject ``server.proxy`` rules into a generated ``vite.config.js``.

    Args:
        content: Existing vite.config.js source.
        target: Backend base URL (e.g. ``http://localhost:8000``).
        prefixes: Path prefixes to forward to the backend in dev.

    Returns:
        Updated vite.config.js source.
    """
    content = _PROXY_BLOCK_RE.sub("\n", content)

    if not prefixes:
        return content

    target = target.rstrip("/")
    unique_prefixes = tuple(
        dict.fromkeys(_normalize_proxy_prefix(p) for p in prefixes if p.strip())
    )
    if not unique_prefixes:
        return content

    proxy_entries = ",\n".join(
        f'      "{prefix}": {{ target: {json.dumps(target)}, changeOrigin: true }}'
        for prefix in unique_prefixes
    )
    proxy_block = (
        f"\n    // {_PROXY_MARKER} (auto-generated by reflex-django)\n"
        f"    proxy: {{\n{proxy_entries},\n    }},\n"
    )

    match = re.search(r"server:\s*\{", content)
    if match is None:
        return content

    brace_pos = match.end() - 1
    newline = content.find("\n", brace_pos)
    insert_at = newline + 1 if newline != -1 else match.end()
    return content[:insert_at] + proxy_block + content[insert_at:]
