"""Patch Reflex's generated Vite config to proxy Django path prefixes in dev."""

from __future__ import annotations

import dataclasses
import json
import re
import time
from pathlib import Path

from reflex_django.core.constants import RESERVED_REFLEX_PREFIXES


@dataclasses.dataclass(frozen=True)
class ViteProxyRoute:
    """A Vite dev-server proxy target and the path prefixes it serves."""

    target: str
    prefixes: tuple[str, ...]

_PROXY_MARKER = "reflex-django-proxy"
_PROXY_PLUGIN_MARKER = "reflex-django-proxy-plugin"
_PROXY_PLUGIN_FILENAME = "vite-plugin-reflex-django-proxy.js"
_PROXY_PLUGIN_IMPORT = (
    'import { reflexDjangoProxyPlugin } from "./vite-plugin-reflex-django-proxy.js";'
)
_PROXY_BLOCK_RE = re.compile(
    r"\n\s*// reflex-django-proxy.*?\n\s*proxy:\s*\{[^}]*\},?\n",
    re.DOTALL,
)
_PROXY_REVISION_RE = re.compile(r"\n// rx-django-proxy-rev: \d+\n?")


def _remove_vite_proxy_block(content: str) -> str:
    """Remove the reflex-django ``server.proxy`` block, including nested braces."""
    marker = f"// {_PROXY_MARKER}"
    idx = content.find(marker)
    if idx == -1:
        return _PROXY_BLOCK_RE.sub("\n", content)

    proxy_idx = content.find("proxy:", idx)
    if proxy_idx == -1:
        return content

    brace_start = content.find("{", proxy_idx)
    if brace_start == -1:
        return content

    depth = 0
    end = brace_start
    for pos in range(brace_start, len(content)):
        char = content[pos]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                end = pos + 1
                while end < len(content) and content[end] in ", \t":
                    end += 1
                if end < len(content) and content[end] == "\n":
                    end += 1
                break

    start = content.rfind("\n", 0, idx)
    start = 0 if start == -1 else start + 1
    return content[:start] + content[end:]


def _normalize_proxy_prefix(prefix: str) -> str:
    if not prefix.startswith("/"):
        prefix = "/" + prefix
    if len(prefix) > 1 and prefix.endswith("/"):
        prefix = prefix.rstrip("/")
    return prefix


def _normalized_prefixes(prefixes: tuple[str, ...]) -> tuple[str, ...]:
    return tuple(
        dict.fromkeys(
            _normalize_proxy_prefix(p) for p in prefixes if p and str(p).strip()
        )
    )


_WS_PROXY_PREFIXES = frozenset({"/_event"})
_ENV_JSON = "env.json"


def vite_dev_proxy_prefixes(django_prefixes: tuple[str, ...]) -> tuple[str, ...]:
    """Django URL prefixes plus Reflex backend endpoints for ``server.proxy``."""
    combined = (*django_prefixes, *RESERVED_REFLEX_PREFIXES)
    return _normalized_prefixes(combined)


def _proxy_entry_line(prefix: str, target: str) -> str:
    target_json = json.dumps(target)
    if prefix in _WS_PROXY_PREFIXES:
        return (
            f'      "{prefix}": '
            f"{{ target: {target_json}, ws: true, changeOrigin: true }}"
        )
    return f'      "{prefix}": {{ target: {target_json}, changeOrigin: true }}'


def _coerce_proxy_routes(
    *,
    routes: tuple[ViteProxyRoute, ...] | None = None,
    target: str | None = None,
    prefixes: tuple[str, ...] | None = None,
) -> tuple[ViteProxyRoute, ...]:
    if routes:
        return tuple(
            ViteProxyRoute(
                target=route.target.rstrip("/"),
                prefixes=_normalized_prefixes(route.prefixes),
            )
            for route in routes
            if route.prefixes
        )
    if target and prefixes:
        normalized = _normalized_prefixes(prefixes)
        if normalized:
            return (ViteProxyRoute(target=target.rstrip("/"), prefixes=normalized),)
    return ()


def _routes_json(routes: tuple[ViteProxyRoute, ...]) -> str:
    payload = [
        {
            "target": route.target.rstrip("/"),
            "prefixes": list(route.prefixes),
        }
        for route in routes
    ]
    return json.dumps(payload, indent=2)


def render_proxy_plugin_js(
    *,
    routes: tuple[ViteProxyRoute, ...] | None = None,
    target: str | None = None,
    prefixes: tuple[str, ...] | None = None,
) -> str:
    """Return source for ``vite-plugin-reflex-django-proxy.js``."""
    coerced = _coerce_proxy_routes(routes=routes, target=target, prefixes=prefixes)
    if not coerced:
        return ""
    routes_json = _routes_json(coerced)
    return f"""// {_PROXY_PLUGIN_MARKER} (auto-generated by reflex-django — do not edit)
import http from "node:http";
import https from "node:https";
import {{ URL }} from "node:url";

const ROUTES = {routes_json};

function matchRoute(pathname) {{
  for (const route of ROUTES) {{
    for (const prefix of route.prefixes) {{
      if (pathname === prefix || pathname.startsWith(prefix + "/")) {{
        return route;
      }}
    }}
  }}
  return null;
}}

export function reflexDjangoProxyPlugin() {{
  const clients = new Map();

  function clientFor(target) {{
    const key = target;
    if (clients.has(key)) {{
      return clients.get(key);
    }}
    const targetUrl = new URL(target);
    const client = targetUrl.protocol === "https:" ? https : http;
    clients.set(key, {{ targetUrl, client }});
    return {{ targetUrl, client }};
  }}

  return {{
    name: "reflex-django-proxy",
    enforce: "pre",
    configureServer(server) {{
      server.middlewares.use((req, res, next) => {{
        const pathname = (req.url ?? "/").split("?")[0];
        const route = matchRoute(pathname);
        if (!route) {{
          return next();
        }}

        const {{ targetUrl, client }} = clientFor(route.target);
        const forwardedHost = req.headers.host;
        const forwardedProto =
          (req.headers["x-forwarded-proto"] ||
            (req.socket?.encrypted ? "https" : "http")) + "";
        const options = {{
          hostname: targetUrl.hostname,
          port:
            targetUrl.port ||
            (targetUrl.protocol === "https:" ? 443 : 80),
          path: req.url,
          method: req.method,
          headers: {{
            ...req.headers,
            host: targetUrl.host,
            "x-forwarded-host": forwardedHost,
            "x-forwarded-proto": forwardedProto,
          }},
        }};

        const proxyReq = client.request(options, (proxyRes) => {{
          res.writeHead(proxyRes.statusCode ?? 502, proxyRes.headers);
          proxyRes.pipe(res, {{ end: true }});
        }});

        proxyReq.on("error", (err) => {{
          if (!res.headersSent) {{
            res.statusCode = 502;
            res.end(`reflex-django proxy error: ${{err.message}}`);
          }}
        }});

        req.pipe(proxyReq, {{ end: true }});
      }});
    }},
  }};
}}
"""


def inject_vite_dev_proxy(
    content: str,
    *,
    routes: tuple[ViteProxyRoute, ...] | None = None,
    target: str | None = None,
    prefixes: tuple[str, ...] | None = None,
) -> str:
    """Inject ``server.proxy`` rules into a generated ``vite.config.js``."""
    content = _remove_vite_proxy_block(content)

    coerced = _coerce_proxy_routes(routes=routes, target=target, prefixes=prefixes)
    if not coerced:
        return content

    proxy_entries = ",\n".join(
        _proxy_entry_line(prefix, route.target)
        for route in coerced
        for prefix in route.prefixes
    )
    proxy_block = (
        f"\n    // {_PROXY_MARKER} (auto-generated by reflex-django)\n"
        f"    proxy: {{\n{proxy_entries},\n    }},\n"
    )

    match = re.search(r"server:\s*\{", content)
    if match is None:
        return content

    brace_pos = match.end() - 1
    newline = content.find("\n", brace_pos)
    insert_at = newline + 1 if newline != -1 else match.end()
    return content[:insert_at] + proxy_block + content[insert_at:]


def inject_vite_proxy_plugin(content: str) -> str:
    """Register :func:`reflexDjangoProxyPlugin` before React Router in Vite plugins."""
    if "reflexDjangoProxyPlugin()" in content:
        return content

    if _PROXY_PLUGIN_IMPORT not in content:
        content = _PROXY_PLUGIN_IMPORT + "\n" + content

    return re.sub(
        r"plugins:\s*\[",
        "plugins: [\n    reflexDjangoProxyPlugin(),",
        content,
        count=1,
    )


def strip_vite_proxy_plugin(content: str) -> str:
    """Remove the reflex-django proxy plugin import and registration from Vite config."""
    content = content.replace(_PROXY_PLUGIN_IMPORT + "\n", "")
    content = content.replace(_PROXY_PLUGIN_IMPORT, "")
    content = re.sub(
        r"\n\s*reflexDjangoProxyPlugin\(\),?",
        "",
        content,
        count=1,
    )
    return content


def strip_vite_dev_proxy(content: str) -> str:
    """Remove ``server.proxy`` rules injected by reflex-django."""
    return _remove_vite_proxy_block(content)


def strip_vite_config_proxy(content: str) -> str:
    """Remove all reflex-django Vite→Django proxy wiring from ``vite.config.js``."""
    content = strip_vite_dev_proxy(content)
    return strip_vite_proxy_plugin(content)


def _stamp_proxy_revision(content: str) -> str:
    """Bump a revision comment so Vite reloads config after post-compile patches."""
    content = _PROXY_REVISION_RE.sub("", content)
    return content.rstrip() + f"\n// rx-django-proxy-rev: {int(time.time() * 1000)}\n"


def patch_vite_config_content(
    content: str,
    *,
    routes: tuple[ViteProxyRoute, ...],
    stamp_revision: bool = True,
) -> str:
    """Apply stability dedupe, proxy plugin, ``server.proxy``, and optional revision stamp."""
    from reflex_django.dev.frontend_stability import patch_vite_react_dedupe

    content = patch_vite_react_dedupe(content)
    content = inject_vite_proxy_plugin(content)
    content = inject_vite_dev_proxy(content, routes=routes)
    if stamp_revision:
        content = _stamp_proxy_revision(content)
    return content


def patch_vite_config(
    content: str,
    *,
    routes: tuple[ViteProxyRoute, ...] | None = None,
    target: str | None = None,
    prefixes: tuple[str, ...] | None = None,
) -> str:
    """Apply plugin import, pre-middleware plugin, and ``server.proxy`` rules."""
    if routes:
        coerced = routes
    elif target and prefixes is not None:
        coerced = (
            ViteProxyRoute(
                target=target,
                prefixes=vite_dev_proxy_prefixes(prefixes),
            ),
        )
    else:
        coerced = ()
    if not coerced:
        from reflex_django.dev.frontend_stability import patch_vite_react_dedupe

        return patch_vite_react_dedupe(content)
    return patch_vite_config_content(content, routes=coerced)


def patch_env_json_for_frontend_proxy(
    web_dir: Path,
    *,
    frontend_port: int,
    backend_port: int,
) -> bool:
    """Point ``env.json`` API URLs at the Vite port (proxied to the Reflex backend)."""
    env_path = Path(web_dir) / "env.json"
    if not env_path.is_file():
        return False

    raw = env_path.read_text(encoding="utf-8")
    backend_host = f"localhost:{backend_port}"
    frontend_host = f"localhost:{frontend_port}"
    if f"localhost:{frontend_port}" in raw and f"localhost:{backend_port}" not in raw:
        return False

    updated = raw.replace(f"http://{backend_host}", f"http://{frontend_host}")
    updated = updated.replace(f"ws://{backend_host}", f"ws://{frontend_host}")
    if updated == raw:
        return False

    env_path.write_text(updated, encoding="utf-8")
    return True


def _vite_proxy_is_complete(
    content: str,
    *,
    routes: tuple[ViteProxyRoute, ...],
) -> bool:
    if "reflexDjangoProxyPlugin()" not in content or _PROXY_MARKER not in content:
        return False
    for route in routes:
        for prefix in route.prefixes:
            if prefix not in content:
                return False
        if route.target not in content:
            return False
    if any(prefix in _WS_PROXY_PREFIXES for route in routes for prefix in route.prefixes):
        return "ws: true" in content
    return True


def _resolve_django_backend_prefixes() -> tuple[str, ...]:
    """Return Django-owned URL prefixes for the Vite dev proxy."""
    from reflex_django.mount.integration_config import mount_enabled
    from reflex_django.mount.prefixes import resolve_prefixes

    prefixes = _normalized_prefixes(resolve_prefixes().backend_prefixes_for_asgi())
    if prefixes:
        return prefixes

    if not mount_enabled():
        return ()

    from reflex_django.mount.discovery import (
        _root_urlconf_urlpatterns,
        discover_django_prefixes,
    )

    patterns = _root_urlconf_urlpatterns()
    if patterns:
        discovered = discover_django_prefixes(patterns)
        if discovered:
            try:
                from reflex_base.utils import console

                console.warn(
                    "reflex-django: discovered Django prefixes from urlpatterns "
                    "for the Vite dev proxy."
                )
            except Exception:
                pass
            return _normalized_prefixes(discovered)
    return ()


def resolve_vite_dev_proxy_routes() -> tuple[ViteProxyRoute, ...]:
    """Resolve Vite proxy route groups for two-port local dev."""
    from reflex_base.config import get_config

    from reflex_django.core.env import resolve_rxdjango_proxy_server

    django_prefixes = _resolve_django_backend_prefixes()
    reflex_prefixes = _normalized_prefixes(RESERVED_REFLEX_PREFIXES)
    config = get_config()
    reflex_target = config.api_url.rstrip("/")
    django_target = resolve_rxdjango_proxy_server() or reflex_target

    if django_target == reflex_target:
        combined = _normalized_prefixes((*django_prefixes, *reflex_prefixes))
        if not combined:
            return ()
        return (ViteProxyRoute(target=reflex_target, prefixes=combined),)

    routes: list[ViteProxyRoute] = []
    if django_prefixes:
        routes.append(
            ViteProxyRoute(
                target=django_target,
                prefixes=django_prefixes,
            )
        )
    if reflex_prefixes:
        routes.append(
            ViteProxyRoute(
                target=reflex_target,
                prefixes=reflex_prefixes,
            )
        )
    return tuple(routes)


def ensure_vite_django_dev_proxy(
    web_dir: Path,
    *,
    routes: tuple[ViteProxyRoute, ...] | None = None,
    target: str | None = None,
    prefixes: tuple[str, ...] | None = None,
    frontend_port: int | None = None,
    backend_port: int | None = None,
    patch_env: bool = False,
    force: bool = False,
) -> bool:
    """Write the proxy plugin file and patch ``.web/vite.config.js``.

    React Router's ``react-router dev`` handles unknown routes before Vite's
    ``server.proxy``; the generated Vite plugin proxies in middleware first.

    Returns:
        ``True`` when any file was created or updated.
    """
    coerced = _coerce_proxy_routes(routes=routes, target=target, prefixes=prefixes)
    if not coerced:
        return False

    web_dir = Path(web_dir)
    changed = False

    plugin_path = web_dir / _PROXY_PLUGIN_FILENAME
    plugin_source = render_proxy_plugin_js(routes=coerced)
    if plugin_source and (
        force
        or not plugin_path.is_file()
        or plugin_path.read_text(encoding="utf-8") != plugin_source
    ):
        plugin_path.write_text(plugin_source, encoding="utf-8")
        changed = True

    vite_path = web_dir / "vite.config.js"
    if not vite_path.is_file():
        return changed

    content = vite_path.read_text(encoding="utf-8")
    if force or not _vite_proxy_is_complete(content, routes=coerced):
        updated = patch_vite_config_content(content, routes=coerced)
        if force or updated != content:
            vite_path.write_text(updated, encoding="utf-8")
            changed = True

    if patch_env and frontend_port is not None and backend_port is not None:
        if patch_env_json_for_frontend_proxy(
            web_dir,
            frontend_port=frontend_port,
            backend_port=backend_port,
        ):
            changed = True

    return changed


def strip_vite_django_dev_proxy(web_dir: Path) -> bool:
    """Remove Vite→Django proxy rules from ``.web/`` when two-port dev is off.

    When the browser uses Django directly, bidirectional Vite ``server.proxy``
    rules would create request loops.

    Returns:
        ``True`` when any file was modified or deleted.
    """
    web_dir = Path(web_dir)
    changed = False

    plugin_path = web_dir / _PROXY_PLUGIN_FILENAME
    if plugin_path.is_file():
        plugin_path.unlink()
        changed = True

    vite_path = web_dir / "vite.config.js"
    if vite_path.is_file():
        content = vite_path.read_text(encoding="utf-8")
        updated = strip_vite_config_proxy(content)
        if updated != content:
            vite_path.write_text(updated, encoding="utf-8")
            changed = True

    return changed


def finalize_web_dev_layout(*, force: bool = True) -> bool:
    """Re-apply stability patches and Vite→Django proxy wiring after compile.

    Writes ``vite.config.js`` once (dedupe + proxy + revision stamp) so Vite
    does not restart on an intermediate compile output missing the proxy plugin.
    """
    from reflex.utils import prerequisites
    from reflex_base.config import get_config
    from reflex_base.utils import console

    from reflex_django.dev.frontend_stability import apply_frontend_stability_patches
    from reflex_django.dev.proxy import dev_uses_separate_ports
    from reflex_django.mount.integration_config import vite_proxy_patching_enabled

    web_dir = Path(prerequisites.get_web_dir())
    if not web_dir.is_dir():
        return False

    if not vite_proxy_patching_enabled():
        changed = strip_vite_django_dev_proxy(web_dir)
        if changed:
            console.info(
                "reflex-django removed Vite proxy rules from .web/ "
                "(ReflexDjangoPlugin proxy.enabled=False)."
            )
        return changed

    if not dev_uses_separate_ports():
        changed = strip_vite_django_dev_proxy(web_dir)
        if changed:
            console.info(
                "reflex-django removed Vite→Django proxy rules from .web/ "
                "(single-port dev — browse :backend_port for UI and API)."
            )
        return changed

    apply_frontend_stability_patches(web_dir)

    routes = resolve_vite_dev_proxy_routes()
    if not routes:
        console.warn(
            "reflex-django: no Vite proxy routes resolved; "
            "/admin and /api may 404 on the frontend port after recompile."
        )
        return False

    config = get_config()
    changed = ensure_vite_django_dev_proxy(
        web_dir,
        routes=routes,
        frontend_port=config.frontend_port,
        backend_port=config.backend_port,
        patch_env=True,
        force=force,
    )
    if changed:
        console.info(
            "reflex-django patched .web/vite.config.js for backend proxies "
            f"({len(routes)} upstream group(s))."
        )
    return changed


def ensure_vite_django_dev_proxy_from_config(*, force: bool = False) -> bool:
    """Patch or strip ``.web/vite.config.js`` using the active Reflex config.

    Two-port dev (``RX_SEPARATE_DEV_PORTS=1``) serves the SPA from
    Vite on ``:frontend_port`` and needs Vite to proxy Django and Reflex backend
    paths to the correct upstreams.

    Single-port dev keeps the browser on Django/Reflex ``:backend_port`` and
    strips bidirectional Vite proxy rules to avoid request loops.
    """
    return finalize_web_dev_layout(force=force)
