"""Shared constants for routing, ports, and environment variable names."""

from __future__ import annotations

RESERVED_REFLEX_PREFIXES: tuple[str, ...] = (
    "/_event",
    "/_upload",
    "/_health",
    "/_all_routes",
    "/ping",
    "/auth-codespace",
)

DEFAULT_FRONTEND_PORT = 3000
DEFAULT_BACKEND_PORT = 8000

ENV_URL_ROUTING = "REFLEX_DJANGO_URL_ROUTING"
ENV_FRONTEND_PORT = "REFLEX_DJANGO_FRONTEND_PORT"
ENV_BACKEND_PORT = "REFLEX_DJANGO_BACKEND_PORT"
ENV_BACKEND_HOST = "REFLEX_DJANGO_BACKEND_HOST"
ENV_SERVE_FROM_BUILD = "REFLEX_DJANGO_SERVE_FROM_BUILD"
ENV_AUTO_EXPORT_ON_START = "REFLEX_DJANGO_AUTO_EXPORT_ON_START"
ENV_DEV_PROXY = "REFLEX_DJANGO_DEV_PROXY"
ENV_COMPILE_DEV = "REFLEX_DJANGO_COMPILE_DEV"
ENV_BACKEND_RELOAD = "REFLEX_DJANGO_BACKEND_RELOAD"
ENV_FRONTEND_PRESENT = "REFLEX_DJANGO_FRONTEND_PRESENT"

SPA_STATIC_SUBDIRS: tuple[str, ...] = ("_reflex", "_static", "reflex")

__all__ = [
    "DEFAULT_BACKEND_PORT",
    "DEFAULT_FRONTEND_PORT",
    "ENV_AUTO_EXPORT_ON_START",
    "ENV_BACKEND_HOST",
    "ENV_BACKEND_PORT",
    "ENV_BACKEND_RELOAD",
    "ENV_COMPILE_DEV",
    "ENV_DEV_PROXY",
    "ENV_FRONTEND_PORT",
    "ENV_FRONTEND_PRESENT",
    "ENV_SERVE_FROM_BUILD",
    "ENV_URL_ROUTING",
    "RESERVED_REFLEX_PREFIXES",
    "SPA_STATIC_SUBDIRS",
]