"""Shared constants for routing, ports, and environment variable names."""

from __future__ import annotations

RESERVED_REFLEX_PREFIXES: tuple[str, ...] = (
    "/_event",
    "/_upload",
    "/_health",
    "/_all_routes",
    "/ping",
    "/auth-codespace",
)

DEFAULT_FRONTEND_PORT = 3000
DEFAULT_BACKEND_PORT = 8000

ENV_PROXY_SERVER = "RX_PROXY_SERVER"
ENV_FRONTEND_PORT = "RX_FRONTEND_PORT"
ENV_BACKEND_PORT = "RX_BACKEND_PORT"
ENV_BACKEND_HOST = "RX_BACKEND_HOST"
ENV_SERVE_FROM_BUILD = "RX_SERVE_FROM_BUILD"
ENV_AUTO_EXPORT_ON_START = "RX_AUTO_EXPORT_ON_START"
ENV_DEV_PROXY = "RX_DEV_PROXY"
ENV_COMPILE_DEV = "RX_COMPILE_DEV"
ENV_BACKEND_RELOAD = "RX_BACKEND_RELOAD"
ENV_FRONTEND_PRESENT = "RX_FRONTEND_PRESENT"

SPA_STATIC_SUBDIRS: tuple[str, ...] = ("_reflex", "_static", "reflex")

__all__ = [
    "DEFAULT_BACKEND_PORT",
    "DEFAULT_FRONTEND_PORT",
    "ENV_AUTO_EXPORT_ON_START",
    "ENV_BACKEND_HOST",
    "ENV_BACKEND_PORT",
    "ENV_BACKEND_RELOAD",
    "ENV_COMPILE_DEV",
    "ENV_DEV_PROXY",
    "ENV_FRONTEND_PORT",
    "ENV_FRONTEND_PRESENT",
    "ENV_PROXY_SERVER",
    "ENV_SERVE_FROM_BUILD",
    "RESERVED_REFLEX_PREFIXES",
    "SPA_STATIC_SUBDIRS",
]
