"""Canonical Django setting and environment variable names for reflex-django."""

from __future__ import annotations

from reflex_django.core.constants import (
    ENV_AUTO_EXPORT_ON_START,
    ENV_BACKEND_HOST,
    ENV_BACKEND_PORT,
    ENV_BACKEND_RELOAD,
    ENV_COMPILE_DEV,
    ENV_DEV_PROXY,
    ENV_FRONTEND_PORT,
    ENV_FRONTEND_PRESENT,
    ENV_PROXY_SERVER,
    ENV_SERVE_FROM_BUILD,
)

SETTING_AUTO_MOUNT = "RX_AUTO_MOUNT"
SETTING_MOUNT_PREFIX = "RX_MOUNT_PREFIX"
SETTING_DJANGO_PREFIX = "RX_DJANGO_PREFIX"
SETTING_RESERVED_REFLEX_PREFIXES = "RX_RESERVED_REFLEX_PREFIXES"
SETTING_PROXY_SERVER = "RX_PROXY_SERVER"

SETTING_CONFIG = "RX_CONFIG"
SETTING_PLUGINS = "RX_PLUGINS"
SETTING_CREATE_APP = "RX_CREATE_APP"
SETTING_VITE_VERSION = "RX_VITE_VERSION"
SETTING_USE_RXCONFIG_FILE = "RX_USE_RXCONFIG_FILE"
SETTING_MATERIALIZE_RXCONFIG = "RX_MATERIALIZE_RXCONFIG"

SETTING_PAGE_PACKAGES = "RX_PAGE_PACKAGES"
SETTING_PAGE_MODULE = "RX_PAGE_MODULE"
SETTING_PAGE_APPS = "RX_PAGE_APPS"

SETTING_DEV_PROXY = "RX_DEV_PROXY"
SETTING_SEPARATE_DEV_PORTS = "RX_SEPARATE_DEV_PORTS"
SETTING_SERVE_FROM_BUILD = "RX_SERVE_FROM_BUILD"
SETTING_AUTO_EXPORT_ON_START = "RX_AUTO_EXPORT_ON_START"
SETTING_RENDER_SPA_VIA_TEMPLATE_ENGINE = "RX_RENDER_SPA_VIA_TEMPLATE_ENGINE"
SETTING_SHOW_BUILT_WITH_REFLEX = "RX_SHOW_BUILT_WITH_REFLEX"

SETTING_RUN_MIDDLEWARE_CHAIN = "RX_RUN_MIDDLEWARE_CHAIN"
SETTING_EVENT_MIDDLEWARE_SKIP = "RX_EVENT_MIDDLEWARE_SKIP"
SETTING_EVENT_BRIDGE_MODE = "RX_EVENT_BRIDGE_MODE"
SETTING_AUTH_ONLY_MIDDLEWARE = "RX_AUTH_ONLY_MIDDLEWARE"
SETTING_EVENT_RESOLVE_URL = "RX_EVENT_RESOLVE_URL"
SETTING_EVENT_BRIDGE_RESOLVER = "RX_EVENT_BRIDGE_RESOLVER"
SETTING_EVENT_CACHE = "RX_EVENT_CACHE"
SETTING_EVENT_CACHE_TTL = "RX_EVENT_CACHE_TTL"
SETTING_EVENT_CACHE_KEY_PREFIX = "RX_EVENT_CACHE_KEY_PREFIX"
SETTING_EVENT_METRICS = "RX_EVENT_METRICS"
SETTING_EVENT_METRICS_LOGGER = "RX_EVENT_METRICS_LOGGER"
SETTING_PERFORMANCE_PRESET = "RX_PERFORMANCE_PRESET"
SETTING_AUTO_REDIRECT_FROM_MIDDLEWARE = "RX_AUTO_REDIRECT_FROM_MIDDLEWARE"
SETTING_EVENT_POST_FROM_PAYLOAD = "RX_EVENT_POST_FROM_PAYLOAD"

SETTING_AUTH = "RX_AUTH"
SETTING_AUTH_AUTO_SYNC = "RX_AUTH_AUTO_SYNC"
SETTING_USER_SNAPSHOT_INCLUDE_GROUPS = "RX_USER_SNAPSHOT_INCLUDE_GROUPS"
SETTING_LOGOUT_PRESERVE_SESSION_KEYS = "RX_LOGOUT_PRESERVE_SESSION_KEYS"
SETTING_MIRROR_MESSAGES = "RX_MIRROR_MESSAGES"
SETTING_MIRROR_CSRF = "RX_MIRROR_CSRF"
SETTING_MIRROR_LANGUAGE = "RX_MIRROR_LANGUAGE"

SETTING_AUTO_SETTINGS = "RX_AUTO_SETTINGS"

__all__ = [
    "ENV_AUTO_EXPORT_ON_START",
    "ENV_BACKEND_HOST",
    "ENV_BACKEND_PORT",
    "ENV_BACKEND_RELOAD",
    "ENV_COMPILE_DEV",
    "ENV_DEV_PROXY",
    "ENV_FRONTEND_PORT",
    "ENV_FRONTEND_PRESENT",
    "ENV_PROXY_SERVER",
    "ENV_SERVE_FROM_BUILD",
    "SETTING_AUTH",
    "SETTING_AUTH_AUTO_SYNC",
    "SETTING_AUTH_ONLY_MIDDLEWARE",
    "SETTING_AUTO_EXPORT_ON_START",
    "SETTING_AUTO_MOUNT",
    "SETTING_AUTO_REDIRECT_FROM_MIDDLEWARE",
    "SETTING_AUTO_SETTINGS",
    "SETTING_CONFIG",
    "SETTING_CREATE_APP",
    "SETTING_DEV_PROXY",
    "SETTING_DJANGO_PREFIX",
    "SETTING_EVENT_BRIDGE_MODE",
    "SETTING_EVENT_BRIDGE_RESOLVER",
    "SETTING_EVENT_CACHE",
    "SETTING_EVENT_CACHE_KEY_PREFIX",
    "SETTING_EVENT_CACHE_TTL",
    "SETTING_EVENT_METRICS",
    "SETTING_EVENT_METRICS_LOGGER",
    "SETTING_EVENT_MIDDLEWARE_SKIP",
    "SETTING_EVENT_POST_FROM_PAYLOAD",
    "SETTING_EVENT_RESOLVE_URL",
    "SETTING_LOGOUT_PRESERVE_SESSION_KEYS",
    "SETTING_MATERIALIZE_RXCONFIG",
    "SETTING_MIRROR_CSRF",
    "SETTING_MIRROR_LANGUAGE",
    "SETTING_MIRROR_MESSAGES",
    "SETTING_MOUNT_PREFIX",
    "SETTING_PAGE_APPS",
    "SETTING_PAGE_MODULE",
    "SETTING_PAGE_PACKAGES",
    "SETTING_PERFORMANCE_PRESET",
    "SETTING_PLUGINS",
    "SETTING_PROXY_SERVER",
    "SETTING_RENDER_SPA_VIA_TEMPLATE_ENGINE",
    "SETTING_RESERVED_REFLEX_PREFIXES",
    "SETTING_RUN_MIDDLEWARE_CHAIN",
    "SETTING_SEPARATE_DEV_PORTS",
    "SETTING_SERVE_FROM_BUILD",
    "SETTING_SHOW_BUILT_WITH_REFLEX",
    "SETTING_USE_RXCONFIG_FILE",
    "SETTING_USER_SNAPSHOT_INCLUDE_GROUPS",
    "SETTING_VITE_VERSION",
]
